---
# file: tasks/main.yml
# Top-level installer for mongodb_exporter.
#
# @see https://github.com/dcu/mongodb_exporter
#

- name: set role variables, if necessary
  include: set-role-variables.yml
    
- name: set internal variables for convenience
  set_fact:
    prometheus_mongodb_exporter_url: "https://github.com/dcu/mongodb_exporter/releases/download/v{{ prometheus_mongodb_exporter_version }}/mongodb_exporter-linux-amd64"
    prometheus_mongodb_exporter_subdir: "{{ prometheus_install_path }}/mongodb_exporter-linux-amd64"

- name: install libselinux-python binary for Ansible to work
  yum: name=libselinux-python state=present
  when: ansible_pkg_mgr == "yum"

- name: create Prometheus group
  group: name=prometheus state=present

- name: create Prometheus user
  user:
    name: prometheus
    group: prometheus
    createhome: no
    shell: /sbin/nologin
    comment: "Prometheus User"
    state: present

- name: mkdir for general cases
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ prometheus_install_path }}"
    - "{{ prometheus_log_path }}"
    - "{{ prometheus_pid_path }}"

- name: download mongodb_exporter
  get_url:
    url: "{{ prometheus_mongodb_exporter_url }}"
    dest: "{{ prometheus_install_path }}/mongodb_exporter"

- name: set permissions, owner and group
  file: path={{ prometheus_install_path }}/mongodb_exporter owner={{ prometheus_user }} group={{ prometheus_group }} mode="a+x"

- name: set prometheus variables
  copy: src="../files/etc-default-mongodb_exporter"  dest=/etc/default/mongodb_exporter

- name: copy INIT script to server
  template: src="../templates/mongodb_exporter.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/mongodb_exporter"  mode="a+x"
  notify:
    - restart mongodb_exporter
  when: not mongodb_exporter_use_systemd|bool

- name: copy systemd config to server
  template: src="../templates/mongodb_exporter.service.j2"  dest="/lib/systemd/system/mongodb_exporter.service"
  when: mongodb_exporter_use_systemd

- name: set INIT status
  service: name=mongodb_exporter enabled=yes state=started
